### ISSUE TITLE
MathProgNLSModel and user-defined functions

### ISSUE THREAD

**Issue by Xx-fractale-xX** [JuliaSmoothOptimizers/NLSProblems.jl#14]
I implemented the mgh07 and mgh35 with MathProgNLSModel that use user-defined functions, nevertheless i have some issues.

For the first one, i find a way to implemented it with only one variable functions. But the MathProgNLSModel didn't find them. ```ERROR: KeyError: key :θ1 not found``` I think that ```MathProgNLSModel``` don't save/read the user-defined functions registered in the JuMP model.

For the second one, i need two variables user-defined functions. And actually JuMP and ForwardDiff package aren't able to calculate Hessian when we have more than one variable. The only workaround of that problem that i see is to give the function ```∇²f``` (if we can calculate it...) or calculate by FiniteDiff (i don't test it but I don't think that it's a good idea with non linear functions). If someone have a solution or an idea for that, it will be great.

The solution that i used in this case is to write the function ```Tsim(x,n)``` of mgh35 (in ```mgh35bis.jl``` file) under the form ```cos(n*Arccos(x))```, classic formula of Chebyshev polynomials.

[mgh07-35.zip](https://github.com/JuliaSmoothOptimizers/NLSProblems.jl/files/2041414/mgh07-35.zip)

**Comment by dpo** [comment]
I can reproduce the issue with `mgh07` (though `θ1` isn't needed).

In `mgh35`, we can't really consider `n` as a variable. We don't want to differentiate with respect to `n`. I tried storing the functions in an array instead:
```julia
  Ts = Vector{Function}(n)
  Tnames = Vector{Symbol}(n)
  for i = 1:n
    Ts[i] = x -> Tsim(2*x-1, i)
    Tnames[i] = gensym()
    JuMP.register(nls, Tnames[i], 2, Ts[i], autodiff=true)
  end
```
but then I'm not sure how to get this to work:
```julia
  @eval @NLexpression(nls, F[i=1:n], sum($(Tnames[i])(x[j]) for j = 1:n)/n - I[i])
```

**Comment by Xx-fractale-xX** [comment]
Yes, it's right ```θ1``` isn't needed in ```mgh07``` but we need at least ```θ2``` because we can't use ```(test ? res1 : res2)``` in an ```@NLexpression```.

For ```mgh35```, i get it "work" with that code:
``` julia
  Ts = Vector{Function}(n)
  Tnames = Vector{Symbol}(n)
  for i = 1:n
    Ts[i] = x -> Tsim(2*x-1, i)
    Tnames[i] =  Symbol("Ts",i) #gensym()
    JuMP.register(nls, Tnames[i], 1, Ts[i], autodiff=true)
  end

  I = [i%2 == 0 ? -1/(i^2-1) : 0 for i = 1:n]
  @NLexpression(nls, F[i=1:n], sum($(Tnames[i])(x[j]) for j = 1:n)/n - I[i])

  return MathProgNLSModel(nls, F, name="mgh35")
```
But we have also the same problem ```KeyError: key :Ts1 not found```.
When we return the ```MathProgNLSModel``` the composants ```F``` in parameter loose access to the user-defined function.
