### ISSUE TITLE
Scalable version of mgh35

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLSProblems.jl#17]
`mgh35` uses a recursive function (the Chebyshev polynomial), and does not scale well. Using the trigonometric definition seems to break something in the differentiation.
Maybe this needs to be defined without using JuMP, or perhaps it can be done with some metaprogramming trick?

**Comment by dpo** [comment]
Could you show what breaks more specifically?

**Comment by Xx-fractale-xX** [comment]
I tried to use an other formulation of ```Tsim``` that isn't recursive and I also have a bunch of ```NaN```.
```julia
function Tsim(x, n)
   p = Int(floor(n/2))
    return sum(binomial(n, 2*k) * (x^2 - 1)^k * x^(n - 2k) for k=0:p)
  end
```

**Comment by Xx-fractale-xX** [comment]
@abel, I investigated the problem. I thought first that ```ForwardDiff``` have difficulty to do the differentiation. It's why I implemented ```∇Tsim``` and ```∇²Tsim```. With user's define function we can give them directly. It was at this moment that I remarked that ```∇Tsim``` and ```∇²Tsim``` weren't define at ```x=1```. Division by zero => ```NaN```.

Can you tell me if you have better results now with that and ```x!=1``` ? 

```julia
  function Tsim(x, n)
    if abs(x) <= 1
      return cos(n * acos(x))
    elseif x > 1
      return cosh(n * acosh(x))
    else
      return (-1)^n * cosh(n * acosh(-x))
    end
  end

  function ∇Tsim(x, n)
    if abs(x) <= 1
      return n * sin(n * acos(x)) / sqrt(1 - x^2)
    elseif x > 1
      return n * sinh(n * acosh(x)) / sqrt(x^2 - 1)
    else
      return -n * (-1)^n * sinh(n * acosh(-x)) / sqrt(x^2 - 1)
    end
  end

  function ∇²Tsim(x, n)
    if abs(x) <= 1
      return n * x * sin(n * acos(x)) / (1 - x^2)^(3/2) - n^2 * cos(n * acos(x)) / (1 - x^2)
    elseif x > 1
      return -n * x * sinh(n * acosh(x)) / (x^2 - 1)^(3/2) + n^2 * cosh(n * acosh(x)) / (x^2 - 1)
    else
      return (-1)^n * n * x * sinh(n * acosh(-x)) / (x^2 - 1)^(3/2) + (-1)^n * n^2 * cosh(n * acosh(x)) / (x^2 - 1)
    end
  end

  Ts = Vector{Function}(n)
  ∇Ts = Vector{Function}(n)
  ∇²Ts = Vector{Function}(n)
  Tnames = Vector{Symbol}(n)

  for i = 1:n
    Ts[i] = x -> Tsim(2*x-1, i)
    ∇Ts[i] = x -> ∇Tsim(2*x-1, i)
    ∇²Ts[i] = x -> ∇²Tsim(2*x-1, i)
    Tnames[i] = gensym()
    JuMP.register(nls, Tnames[i], 1, Ts[i], ∇Ts[i], ∇²Ts[i])
  end
```

**Comment by abelsiqueira** [comment]
@Xx-fractale-xX, the problem is that the polynomial is differentiable at 1.0, so we should be able to have it's derivative. I haven't tested it, but registering all derivatives, we can make a check for `x == 1.0` and `x == -1.0` to explicitly define the derivative value.

**Comment by dpo** [comment]
Should this be closed now that we're removing that problem?

**Comment by abelsiqueira** [comment]
Yes, thanks.
