### ISSUE TITLE
Tutorial on usage would be great!

### ISSUE THREAD

**Issue by antoinerincent** [JuliaSmoothOptimizers/NLSProblems.jl#48]
Awesome package to test out the effectiveness of numerical methods, but newbies like me really struggle to use the package without examples of usage!

Thanks! :)

**Comment by abelsiqueira** [comment]
Hi @antoinerincent, thanks for the interest. Indeed, we have a lot of work to do yet with documentation/tutorials. There will be some in the future on our site: juliasmoothoptimizers.github.io. For now, let me know if you need some help.
